version: "3.8"

services:
  db-origem:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ORIGEM}
      POSTGRES_USER: ${POSTGRES_USER_ORIGEM}
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/modelo_relacional.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src\database\db_volume:/var/lib/postgresql/data # volume do bd
    networks:
      - my_network

networks:
  my_network:
    driver: bridge