version: "3.8"

services:
  db-origem:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "mcds123origem"
      POSTGRES_USER: "user_origem"
    ports:
      - "5432:5432"
    volumes:
      - /c/log_postgres/origem:/var/lib/postgresql/data