-- garantir unicidade dos dados
CREATE UNIQUE INDEX IQ_PAIS ON TB_PAIS (NOME, CAPITAL, CONTINENTE); 
CREATE UNIQUE INDEX IQ_ESTADO ON TB_ESTADO (NOME, SIGLA, ID_PAIS);
CREATE UNIQUE INDEX IQ_CIDADE ON TB_CIDADE (ID_IBGE);
CREATE UNIQUE INDEX IQ_REGIAO ON TB_REGIAO(LATITUDE,LONGITUDE);

